In [30]:
import torch
from torch.utils.data import TensorDataset, DataLoader

#dataset = torch.load('data.pt')
#label = torch.load('label.pt')

tensor_x = torch.load('data.pt') # transform to torch tensor
tensor_y = torch.load('label.pt')

def custom_one_hot_encode(data):
    x = torch.DoubleTensor([[1, 0, 0, 0, 0, 0, 0],
                            [0, 1, 0, 0, 0, 0, 0],
                            [0, 0, 1, 0, 0, 0, 0],
                            [0, 0, 0, 1, 0, 0, 0],
                            [0, 0, 0, 0, 1, 0, 0],
                            [0, 0, 0, 0, 0, 1, 0],
                            [0, 0, 0, 0, 0, 0, 1],
                            [0, 0, 0, 0, 0, 0, 0],])
    return x[data.to(torch.int64)]
    
def custom_one_hot_decode(data):
    x = torch.LongTensor([0, 1, 2, 3, 4, 5, 6, 7])
    
    return x[data]

print(tensor_y)
encode_result = custom_one_hot_encode(tensor_y)
decode_result = custom_one_hot_decode(encode_result)
print(decode_result)

#torch_dataset = TensorDataset(tensor_x,tensor_y) # create your datset
#torch_dataloader = DataLoader(torch_dataset) # create your dataloader

tensor([5., 0., 4.,  ..., 1., 3., 3.])


IndexError: tensors used as indices must be long, byte or bool tensors

In [14]:
print(torch_dataset[0])

(tensor([[9.1244e-13, 8.8116e-12, 6.9113e-11,  ..., 4.9584e-11, 7.4643e-12,
         9.1244e-13],
        [7.4643e-12, 7.2083e-11, 5.6536e-10,  ..., 4.7885e-10, 7.2083e-11,
         8.8116e-12],
        [4.9584e-11, 4.7885e-10, 3.7557e-09,  ..., 3.7557e-09, 5.6536e-10,
         6.9113e-11],
        ...,
        [6.9113e-11, 5.6536e-10, 3.7557e-09,  ..., 3.7557e-09, 4.7885e-10,
         4.9584e-11],
        [8.8116e-12, 7.2083e-11, 4.7885e-10,  ..., 5.6536e-10, 7.2083e-11,
         7.4643e-12],
        [9.1244e-13, 7.4643e-12, 4.9584e-11,  ..., 6.9113e-11, 8.8116e-12,
         9.1244e-13]]), tensor(5.))


In [8]:
label_map = {'fock_dm': 0,
            'coherent_dm':1,
            'thermal_dm':2,
            'num':3,
            'binomial':4,
            'cat':5,
            'gkp':6,
            'random':7}

import torch.nn.functional as F

x = torch.tensor([0, 1, 2, 3, 4, 5, 6, 7])
F.one_hot(x, num_classes=8)

tensor([[1, 0, 0, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0, 0, 0],
        [0, 0, 1, 0, 0, 0, 0, 0],
        [0, 0, 0, 1, 0, 0, 0, 0],
        [0, 0, 0, 0, 1, 0, 0, 0],
        [0, 0, 0, 0, 0, 1, 0, 0],
        [0, 0, 0, 0, 0, 0, 1, 0],
        [0, 0, 0, 0, 0, 0, 0, 1]])

In [ ]:
from torch import nn

class GaussianNoise(nn.Module):
    """Apply additive zero-centered Gaussian noise.
    This is useful to mitigate overfitting
    (you could see it as a form of random data augmentation).
    Gaussian Noise (GS) is a natural choice as corruption process
    for real valued inputs.
    As it is a regularization layer, it is only active at training time.
    Args:
      stddev: Float, standard deviation of the noise distribution.
    Call arguments:
      inputs: Input tensor (of any rank).
    Input shape:
      Arbitrary. Use the keyword argument `input_shape`
      (tuple of integers, does not include the samples axis)
      when using this layer as the first layer in a model.
    Output shape:
      Same shape as input.
    """

    def __init__(self, 
                 std, 
                 mean=0.):
        super().__init__()
        self.mean = mean
        self.std = std

    def foward(self, x):
        return x + torch.randn(x.size())*self.std + self.mean

class Classifier(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = nn.Conv2d(1, 32, 3, bias=False)
        self.leaky_relu = nn.LeakyReLU()
        self.conv2 = nn.Conv2d(1, 32, 3, bias=False)
        self.drop_out = nn.Dropout(p=0.4)
        self.noise = AddGaussianNoise(0.005)

    def forward(self, x):
        x = self.conv1(x)
        x = self.leaky_relu(x)
        x = self.conv2(x)
        x = self.leaky_relu(x)
        x
        
        
        return logits
    
    
    inp = tf.keras.layers.Input(shape=[32, 32, 1], name='input_image')
    x = tf.keras.layers.Conv2D(32, 3, strides=1,
                               use_bias=False,
                              )(inp)
    x = tf.keras.layers.LeakyReLU()(x)

    x = tf.keras.layers.Conv2D(32, 3, strides=1,
                               use_bias=False,
                              )(x)
    x = tf.keras.layers.LeakyReLU()(x)

    x = tf.keras.layers.GaussianNoise(0.005)(x)
    x = tf.keras.layers.Dropout(0.4)(x) 
    
    x = tf.keras.layers.Conv2D(32, 3, strides=2,
                               use_bias=False)(x)
    x = tf.keras.layers.LeakyReLU()(x)
    

    x = tf.keras.layers.Conv2D(64, 3, strides=1,
                              use_bias=False)(x)
    x = tf.keras.layers.LeakyReLU()(x)
    
    x = tf.keras.layers.GaussianNoise(0.005)(x)
    x = tf.keras.layers.Dropout(0.4)(x)    
    
    x = tf.keras.layers.Conv2D(64, 3, strides=1,
                              use_bias=False)(x)
    x = tf.keras.layers.LeakyReLU()(x)
    
    x = tf.keras.layers.Conv2D(64, 3, strides=2,
                              use_bias=False)(x)
    x = tf.keras.layers.LeakyReLU()(x)

    x = tf.keras.layers.Dropout(0.4)(x)
    
    x = tf.keras.layers.Flatten()(x)
    x = tf.keras.layers.Dense(512)(x)
    x = tf.keras.layers.LeakyReLU()(x)
    
    x = tf.keras.layers.Dropout(0.4)(x)    
    
    x = tf.keras.layers.Dense(256)(x)
    x = tf.keras.layers.LeakyReLU()(x)
    
    x = tf.keras.layers.Dense(7)(x)

    return tf.keras.Model(inputs=inp, outputs=x)